### ISSUE TITLE
Как сделать добавление нескольких элементов?

### ISSUE THREAD

**Issue by maxim-kn-akvilon** [mackrais/yii2-btn-copy-html-block#1]
Есть ли возможность проставлять дополнительные индексы в имена полей?
При добавлении полей по подобному шаблону:
<?= $form->field($model->fields, '[]title')->checkbox() ?>
<?= $form->field($model->fields, '[]description')->checkbox() ?>
получается массив 
[
    [0] => [title => val],
    [1] => [description=> val],
    [2] => [title => val],
    [3] => [description=> val],
]
Есть ли возможность сделать так, чтоб приходило во так???
[
    [0] => [
       title => val,
       description=> val
    ],
    [1] => [
       title => val,
       description=> val
    ],
]

**Comment by mackrais** [comment]
@maxim-kn-akvilon 
**1 Вариант**
field($model->fields, 'description[]')->checkbox()
field($model->fields, 'title[]')->checkbox() 
В этом случае вы получите такой массив
[
    'description'=>[  0=> val, 1 => val  ],
    'title'=>[  0=> val, 1 => val  ],
]

Тогда если у вас допустим поле заголовок является обязательным мы принимаем его как максимальное  тогда после $model->load(Yii::$app->requset->post()) или иного метода обработки пишем цикл

foreach($model->title as $key => $value){
      $model->title[$key];
      $model->description[$key];
}

**1 Вариант**
Или используя событие

```
"afterInsertBlock"=>'afterClone (event, $this, $cloneBlock, $tmpBlock)'
```

 ```
function afterClone(event, $this, $cloneBlock, $tmpBlock) {
    var cloneIndex = $($this.data('mr-clone-block')).length;
    $tmpBlock.find('input').each(function(){
         var name = $(this).attr('name');
         name = name.replace(/\[(\d|)\]/g,"")+"["+cloneIndex+"]";
         $(this).attr('name', name);
    });
}
```

**Примеры писал без проверки**
